[project]
name = "movie-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nornir>=3.5.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
